"""rename department

Revision ID: 22b9dbbd9431
Revises: 3d0cbdf2e385
Create Date: 2025-01-22 02:22:09.609038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b9dbbd9431'
down_revision = '3d0cbdf2e385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###
