"""rename address

Revision ID: d99d87f81aee
Revises: 22b9dbbd9431
Create Date: 2025-01-22 02:27:51.235917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99d87f81aee'
down_revision = '22b9dbbd9431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'location',  new_column_name='address')
    # ### end Alembic commands ###
